service: test-service

plugins:
  - serverless-python-requirements
provider:
  name: aws
  region: us-east-1
  stackName: test-service
  runtime: python3.8
  stackTags:
    Project: sasa-project
  apiGateway:
    restApiId: ${cf:e-learning-infra.apiGatewayId}
    restApiRootResourceId: ${cf:e-learning-infra.apiGatewayResourceId}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - rds-data:*
      Resource: "*"
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: "*"

custom:
  pythonRequirements:
    dockerizePip: non-linux

layers:
  db:
    path: ../layers/db-layer

functions:
  createTest:
    handler: create-test/main.handler
    layers:
      - { Ref: DbLambdaLayer }
    environment:
      DB_CLUSTER_ARN: 'arn:aws:rds:us-east-1:832311466616:cluster:aurora-postgresql-cluster-v1'
      DB_SECRET_ARN: 
        ${cf:e-learning-infra.rdsClusterSecretArn}
      DB_NAME: 'elearning'
    events:
      - http:
          path: /test/
          method: post
          cors: true
  getTest:
    handler: get-test/main.handler
    layers:
      - { Ref: DbLambdaLayer }
    environment:
      DB_CLUSTER_ARN: 'arn:aws:rds:us-east-1:832311466616:cluster:aurora-postgresql-cluster-v1'
      DB_SECRET_ARN: 
        ${cf:e-learning-infra.rdsClusterSecretArn}
      DB_NAME: 'elearning'
    events:
      - http:
          path: /test/{course_id}
          method: get
          cors: true
  listTest:
    handler: list-courses/main.handler
    layers:
      - { Ref: DbLambdaLayer }
    environment:
      DB_CLUSTER_ARN: 'arn:aws:rds:us-east-1:832311466616:cluster:aurora-postgresql-cluster-v1'
      DB_SECRET_ARN: 
        ${cf:e-learning-infra.rdsClusterSecretArn}
      DB_NAME: 'elearning'
    events:
      - http:
          path: /test
          method: get
          cors: true
          request:
            application/json: '{ "limit" : "$input.params(''limit'')", "offset": "$input.params(''offset'')" }'
  deleteTest:
    handler: delete-test/main.handler
    layers:
      - { Ref: DbLambdaLayer }
    environment:
      DB_CLUSTER_ARN: 'arn:aws:rds:us-east-1:832311466616:cluster:aurora-postgresql-cluster-v1'
      DB_SECRET_ARN: 
        ${cf:e-learning-infra.rdsClusterSecretArn}
      DB_NAME: 'elearning'
    events:
      - http:
          path: /test/{course_id}
          method: delete
          cors: true

package:
  exclude:
    - node_modules/**
    - set_env_vars.sh
    - package.json
    - package-lock.json
    - README.md