service: course-service

plugins:
  - serverless-python-requirements

provider:
  name: aws
  region: us-east-1
  stackName: course-service
  runtime: python3.8
  stackTags:
    Project: sasa-project
  apiGateway:
    restApiId: ${cf:e-learning-infra.apiGatewayId}
    restApiRootResourceId: ${cf:e-learning-infra.apiGatewayResourceId}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - rds-data:*
      Resource: "*"
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: "*"

custom:
  pythonRequirements:
    dockerizePip: non-linux

layers:
  db:
    path: ../layers/db-layer

functions:
  createCourse:
    handler: create-course/main.handler
    layers:
      - { Ref: DbLambdaLayer }
    environment:
      DB_CLUSTER_ARN: 'arn:aws:rds:us-east-1:832311466616:cluster:aurora-postgresql-cluster-v1'
      DB_SECRET_ARN: 
        ${cf:e-learning-infra.rdsClusterSecretArn}
      DB_NAME: 'elearning'
    events:
      - http:
          path: /v1/course/
          method: post
          cors: true
  getCourse:
    handler: get-course/main.handler
    layers:
      - { Ref: DbLambdaLayer }
    environment:
      DB_CLUSTER_ARN: 'arn:aws:rds:us-east-1:832311466616:cluster:aurora-postgresql-cluster-v1'
      DB_SECRET_ARN: 
        ${cf:e-learning-infra.rdsClusterSecretArn}
      DB_NAME: 'elearning'
    events:
      - http:
          path: /v1/course/{course_id}
          method: get
          cors: true
  listCourse:
    handler: list-courses/main.handler
    layers:
      - { Ref: DbLambdaLayer }
    environment:
      DB_CLUSTER_ARN: 'arn:aws:rds:us-east-1:832311466616:cluster:aurora-postgresql-cluster-v1'
      DB_SECRET_ARN: 
        ${cf:e-learning-infra.rdsClusterSecretArn}
      DB_NAME: 'elearning'
    events:
      - http:
          path: /v1/course
          method: get
          cors: true
          request:
            application/json: '{ "limit" : "$input.params(''limit'')", "offset": "$input.params(''offset'')" }'
  deleteCourse:
    handler: delete-course/main.handler
    layers:
      - { Ref: DbLambdaLayer }
    environment:
      DB_CLUSTER_ARN: 'arn:aws:rds:us-east-1:832311466616:cluster:aurora-postgresql-cluster-v1'
      DB_SECRET_ARN: 
        ${cf:e-learning-infra.rdsClusterSecretArn}
      DB_NAME: 'elearning'
    events:
      - http:
          path: /v1/course/{course_id}
          method: delete
          cors: true
  startCourse:
    handler: start-course/main.handler
    layers:
      - { Ref: DbLambdaLayer }
    environment:
      DB_CLUSTER_ARN: 'arn:aws:rds:us-east-1:832311466616:cluster:aurora-postgresql-cluster-v1'
      DB_SECRET_ARN: 
        ${cf:e-learning-infra.rdsClusterSecretArn}
      DB_NAME: 'elearning'
    events:
      - http:
          path: /v1/course/{course_id}/start
          method: post
          cors: true
  progressCourse:
    handler: progress-course/main.handler
    layers:
      - { Ref: DbLambdaLayer }
    environment:
      DB_CLUSTER_ARN: 'arn:aws:rds:us-east-1:832311466616:cluster:aurora-postgresql-cluster-v1'
      DB_SECRET_ARN: 
        ${cf:e-learning-infra.rdsClusterSecretArn}
      DB_NAME: 'elearning'
    events:
      - http:
          path: /v1/course/{course_id}/user/{user_id}/progress
          method: put
          cors: true

package:
  exclude:
    - node_modules/**
    - set_env_vars.sh
    - package.json
    - package-lock.json
    - README.md