service: sls-create-product

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    restApiId: ${cf:sls-api-gateway-dev.apiGatewayId}
    restApiRootResourceId: ${cf:sls-api-gateway-dev.apiGatewayResourceId}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
      Resource: ${cf:sls-dynamo-db-${opt:stage}.ProductTableArn}

functions:
  api:
    handler: lambda.handler
    environment: 
      TABLE_NAME: sls-products
    events:
      - http:
          path: /product-create
          method: post
          cors: true
