service: sls-aurora-v4

provider: aws
functions: 

# TODO:
# jumpbox creation (maybe ...)
# Migration
resources:
  Resources:
    RDSCluster:
      Type: 'AWS::RDS::DBCluster'
      Properties:
        MasterUsername: postgres
        MasterUserPassword: postgres
        DBClusterIdentifier: aurora-postgresql-cluster
        Engine: aurora-postgresql
        EngineMode: serverless
        EngineVersion: '10.14'
        DBClusterParameterGroupName: default.aurora-postgresql10
        ScalingConfiguration:
          AutoPause: true
          MinCapacity: 2
          MaxCapacity: 4