service: sls-api-gateway

provider: aws
functions:

resources:
  Resources:
    APIGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: sls-api-gateway
    ApiGatewayauthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        IdentitySource: method.request.header.Authorization
        RestApiId: !Ref APIGateway
        Type: COGNITO_USER_POOLS
        Name: ApiGatewayAuthorizer
        ProviderARNs:
          - Fn::Join:
            - ':'
            - - 'arn:aws:cognito-idp'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - !Join
                - '/'
                - - 'userpool'
                  - ${cf:sls-cognito-${opt:stage}.userPoolId}

  Outputs:
    apiGatewayResourceId:
      Description: The root resource id of the api gateway
      Value: !GetAtt APIGateway.RootResourceId
      Export:
        Name: sls-api-gateway-resource-id
    apiGatewayId:
      Description: The id of the api gateway
      Value: !Ref APIGateway
      Export:
        Name: sls-api-gateway-id
    
