service: aurora-serverless

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - rds-data:ExecuteStatement
        - rds-data:BeginTransaction
        - rds-data:RollbackTransaction
        - rds-data:CommitTransaction
      Resource: "*"
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: "*"

custom:
  DBClusterARN:
    Fn::Join:
      - ':'
      - - 'arn:aws:rds'
        - Ref: 'AWS::Region'
        - Ref: 'AWS::AccountId'
        - 'cluster'
        - Fn::ImportValue: 'sls-aurora-dev.rdsClusterArn'

functions:
  DBMigration:
    name: DBMigration
    description: Executes DB Schema Migrations.
    handler: db.handler
    memorySize: 512
    timeout: 100
    environment:
      DB_CLUSTER_ARN:
        ${self:custom.DBClusterARN}
      DB_SECRET_ARN: 
        ${cf:sls-aurora-dev.rdsClusterSecretArn}
      DB_NAME: 'rds_demo_db'

package:
  exclude:
    - node_modules/**
    - set_env_vars.sh
    - package.json
    - package-lock.json
    - README.md