name: Serverless manual deploy pipeline
on: [workflow_dispatch]

jobs:
  deploy_infra_deps:
    name: Deploy infra deps
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: deploy infra-deps
        run: | 
          npm install -g serverless
          chmod 777 ./deployment/serverless_deploy.sh
          ./deployment/serverless_deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          FOLDER: 'infrastructure-deps/'

  deploy_infra:
    name: Deploy infra
    needs: deploy_infra_deps
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: deploy infra
        run: | 
          npm install -g serverless
          chmod 777 ./deployment/serverless_deploy.sh
          ./deployment/serverless_deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          FOLDER: 'infrastructure/'

  deploy_backend:
    name: Deploy backend
    runs-on: ubuntu-latest
    needs: deploy_infra
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build backend
        run: |
          chmod 777 ./deployment/build_backend.sh
          ./deployment/build_backend.sh
      - name: deploy backend
        run: | 
          npm install -g serverless
          chmod 777 ./deployment/serverless_deploy.sh
          ./deployment/serverless_deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          FOLDER: 'backend/'

    